// Generated by flute sync. Edit recipes and components, not this registry.
import recipe0 from "./scenes/connected-opportunity-tour.scene.json";
import recipe1 from "./scenes/demand-picture-modal.scene.json";
import recipe2 from "./scenes/idea-market-snapshot.scene.json";
import recipe3 from "./scenes/money-math-modal.scene.json";
import recipe4 from "./scenes/opportunity-mining-scanner.scene.json";
export const sceneModules = {
  "src/flute/scenes/connected-opportunity-tour.scene.json": async () => ({default:recipe0}),
  "src/flute/scenes/connected-opportunity-tour.tsx": () => import("./scenes/connected-opportunity-tour"),
  "src/flute/scenes/demand-picture-modal.scene.json": async () => ({default:recipe1}),
  "src/flute/scenes/demand-picture-modal.tsx": () => import("./scenes/demand-picture-modal"),
  "src/flute/scenes/idea-market-snapshot.scene.json": async () => ({default:recipe2}),
  "src/flute/scenes/idea-market-snapshot.tsx": () => import("./scenes/idea-market-snapshot"),
  "src/flute/scenes/money-math-modal.scene.json": async () => ({default:recipe3}),
  "src/flute/scenes/money-math-modal.tsx": () => import("./scenes/money-math-modal"),
  "src/flute/scenes/opportunity-mining-scanner.scene.json": async () => ({default:recipe4}),
  "src/flute/scenes/opportunity-mining-scanner.tsx": () => import("./scenes/opportunity-mining-scanner"),
};
